### ISSUE TITLE
Ios > safari : clicking/tapping is not working

### ISSUE THREAD

**Issue by danmihaila** [davidmegginson/e6b#2]
I was trying to tap to get an answer for a question. No area seems to work except the logo, but this means it will show the answer and then redirect to homepage.

**Comment by davidmegginson** [comment]
Possible help here: https://stackoverflow.com/questions/13346202/window-click-does-not-fire-on-safari-for-ipad

**Comment by davidmegginson** [comment]
Using touchstart/touchend isn't working well, even after disabling passive mode and using preventDefault(). There's more information here about the Safari click-event bug: https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

**Comment by davidmegginson** [comment]
@danmihaila - it might be working now (I can't test). Could you give it a shot when you have a chance and let me know?

**Comment by danmihaila** [comment]
It is working now! 

Dan Mihaila

**Comment by davidmegginson** [comment]
Thanks! That's great news. I really appreciate your help.
